name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build with environment variables
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        # HTML 파일에 환경 변수 주입
        sed -i "s|window.SUPABASE_URL \|\| 'PLACEHOLDER_URL'|'$SUPABASE_URL'|g" board.html
        sed -i "s|window.SUPABASE_ANON_KEY \|\| 'PLACEHOLDER_KEY'|'$SUPABASE_ANON_KEY'|g" board.html
        
        # index.html에도 필요시 적용
        if grep -q "SUPABASE" index.html; then
          sed -i "s|window.SUPABASE_URL \|\| 'PLACEHOLDER_URL'|'$SUPABASE_URL'|g" index.html
          sed -i "s|window.SUPABASE_ANON_KEY \|\| 'PLACEHOLDER_KEY'|'$SUPABASE_ANON_KEY'|g" index.html
        fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: >-
          .github,
          README.md,
          .gitignore,
          .env,
          .env.example,
          .kiro,
          *.py,
          test_*.html,
          MCP_SETUP.md,
          SUPABASE_SETUP.md